# Generated by Django 5.1.1 on 2024-10-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField()),
                ('copyright', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
