# Generated by Django 5.1.1 on 2024-10-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
