# Generated by Django 5.1.1 on 2024-10-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_home_address_home_email_home_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='contact_img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
