# Generated by Django 5.1.1 on 2024-10-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_home_contact_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='contact_headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
