# Generated by Django 5.1.1 on 2024-12-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='website',
        ),
    ]
