# Generated by Django 5.1.1 on 2024-12-03 04:13

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='contact_img',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='Blog_website_img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='Blog_website_img'),
        ),
    ]
